dist: xenial
os: linux
language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/Gemfile.rails-5.0.x
install:
  - "sudo pip install --upgrade pip"
  - "sudo pip install awsebcli --ignore-installed"
  - "gem install bundler"
  - "bundle install"

script:
   - "export EXCEPT_DEPLOYED=true"
   - "if [[ $TRAVIS_RUBY_VERSION == '2.6' ]]; then export EXCEPT_DEPLOYED=false; fi"
   - "bundle exec rspec spec"
